[package]
name = "my_proc_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event = { path = "../event" }
crossterm.workspace = true
regex.workspace = true

[lib]
proc-macro = true
