[book]
authors = ["wongjiahau"]
language = "en"
multilingual = false
src = "src"
title = "Ki Editor"

# Check for borken links
# See https://github.com/Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck]
traverse-parent-directories = true

